### ISSUE TITLE
Presentation of results for continuous outcomes

### ISSUE THREAD

**Issue by Lachlan-Cribb** [yqzhong7/AIPW#39]
Hi, thanks for the fantastic package! I have a small suggestion. Would you be able to change the text included with the results output to something like 'exposure mean', 'control mean' and 'mean difference' when the outcome is continuous? Otherwise it can be a bit confusing seeing 'risk difference' etc for a continuous outcome. 

Here is a quick reprex to demonstrate the issue: 

```
A <- rbinom(100, 1, 0.5)
W <- rnorm(100)
Y <- rnorm(100)

aipw_out <- aipw_wrapper(
  Y = Y,
  A = A,
  W = W,
  Q.SL.library = "SL.mean",
  g.SL.library = "SL.mean",
  k = 1
)
```

```
                 Estimate    SE 95% LCL 95% UCL   N
Risk of exposure  -0.2493 0.133  -0.511  0.0124  51
Risk of control   -0.0778 0.126  -0.325  0.1697  49
Risk Difference   -0.1714 0.183  -0.531  0.1879 100
```

**Comment by yqzhong7** [comment]
Thank you for your comments! I've changed the outputs for continuous outcomes in the dev branch, and will incorporate this change into the next CRAN version.
