### ISSUE TITLE
prediction for goodness of fit calculation

### ISSUE THREAD

**Issue by andrea-giovannetti** [yqzhong7/AIPW#48]
Hi @yqzhong7 
I really appreciate your work with this package. I would like to ask what is the right way to use the sl.predict( ) command in this setting. I was under the assumption it sufficed to run predict(fitted_aipw_model, XX_target) but if I try this route, I get the following error:

no applicable method for 'predict' applied to an object of class "c('AIPW', 'AIPW_base', 'R6')

I would like to understand what to do. My purpose is to test AUC for evaluating model precision for a simple binary treatment, if that makes sense. thanks!

**Comment by yqzhong7** [comment]
Hi @andrea-giovannetti, sl.fit() and sl.predict() methods are essentially wrapper functions of the Superleaner or sl3. If you want to estimate the AUC of the binary treatment model, you will need to use the same learners and create your own superlearner. However, the AIPW package uses cross-fitting by default, and the AUC from Superlearner that you created for your treatment model may not be the same as the AUC from the AIPW package.

**Comment by andrea-giovannetti** [comment]
Thank you!
