### ISSUE TITLE
For continuous outcomes, treatment is not modeled as binary

### ISSUE THREAD

**Issue by ngreifer** [yqzhong7/AIPW#49]
When the outcome is continuous, the treatment is also considered continuous because the `$sl.fit()` function uses `family = private$Y.type` even for the treatment. This means you can't use methods designed for binary models (e.g., `"SL.lda"`) and all models that are used treat the treatment as continuous, meaning linear models are used and propensity scores can be negative or greater than 1.

**Comment by yqzhong7** [comment]
Thank you for pointing this out!
